<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "templatemaker"
 *
 * Auto generated by Extension Builder 2016-02-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Template Maker',
	'description' => 'The template maker tool for the t3bootstrap.de project. You will need the t3bootstrap template.',
	'category' => 'plugin',
	'author' => 'Sven Wappler',
	'author_email' => 'typo3YYYY@wappler.systems',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.6',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.7.99',
            'demotemplate' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);